version: '3.1'
 node:
    build: .
    command: npm run start

    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "sql"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456789"
    ports:
      - "5432:5432"